version : '3'
services:
  poll:
    build:
      context: ./poll
      dockerfile: Dockerfile
    image: poll:latest
    ports:
      - 5000:80
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: worker:latest
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    image: result:latest
    ports:
      - 5001:80
